# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
production:
  database: hotpocket_production
  username: postgres
  password:
  host: localhost
  encoding: utf8
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  database: hotpocket_development
  username: postgres
  password:
  host: localhost
  encoding: utf8
  adapter: postgresql
  pool: 5
  timeout: 5000

test: &test
  database: hotpocket_test
  username: postgres
  password:
  host: localhost
  encoding: utf8
  adapter: postgresql
  pool: 5
  timeout: 5000

