development:
  access_key_id: AKIAJFBKDNRFEQF3SCXQ
  secret_access_key: 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
  bucket: hotpocket
# production:
  # access_key_id: AKIAJFBKDNRFEQF3SCXQ
  # secret_access_key: 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
  # bucket: mygreatapp-production
